### ISSUE TITLE
Thunderbird message %a produces invalid HTML

### ISSUE THREAD

**Issue by bebehei** [mkiol/GNotifier#192]
Hi,

as the notification server should understand some a small subset of HTML tags, it also want's to parse the E-mail Address in the default title (`%a` => `User Name <user@name.com>`) as a tag. So, depending on the server, `<user@name.com>` either gets dropped or shown.

The `<>` should get properly escaped. The problem should be somewhere around here: https://github.com/mkiol/GNotifier/blob/master/source/lib/thunderbird.js#L430

I'm using the addon version from current master and Thunderbird 52.3.0.

For a possible workaround, you could use `%n &lt;%m&gt;` in the title (which should be the escaped equivalent).

But anyway: Thanks for that awesome plugin!

**Comment by mkiol** [comment]
I 100% agree. 

According this [spec](https://developer.gnome.org/notification-spec/#markup) only following tags are mandatory to support on server side: \<b>, \<i>, \<u>, \<a>, \<img> and nothing more. Gnotifier should discard every unsupported HTML symbols before sending data to notification server.

This issue is related to #185 and #24

**Comment by bebehei** [comment]
>  Gnotifier should discard every unsupported HTML symbols before sending data to notification server.

Someone from the dunst team mentioned this, too: You should check for the caps of the server. If the server doesn't support `body-markup`, you do not have to escape the content.

**Comment by mkiol** [comment]
I will fix this bug in the next release.

**Comment by mkiol** [comment]
The Issue has been fixed in the latest dev xpi.

**Comment by bebehei** [comment]
> The Issue has been fixed in the latest dev xpi.

Yay, thanks for taking care of this. But I've built the plugin from current master (1b38ebff), and it seems, that `%a` still sends unescaped tags. From my point of view, this is not fixed.

**Comment by mkiol** [comment]
@bebehei 
Are you referring to escaping of Summary/Title field? As per [spec](https://developer.gnome.org/notification-spec/#markup) only Body supports some HTML tags, so it should be escaped. The Summary/Title field doesn't recognize HTML and therefore it should be pass to the notification server without modifications. Actually, GNOME and KDE display Title correctly without any escaping.

Body escaping is implemented here: https://github.com/mkiol/GNotifier/blob/master/source/lib/linux.js#L406. I have tested it several times and it works! I'm pretty sure.

**Comment by bebehei** [comment]
Ouch. I see, the fault is on my side.

You're reading the specs very carefully. Very good work!
